# Site settings
title: Davide Reppucci | Team leader - Technical project manager - Front-end developer
email: davide.reppucci@gmail.com
description: Write an awesome description for your new site here. You can edit this
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dreppucci.github.io" # the base hostname & protocol for your site
twitter_username: davidereppucci
github_username:  dreppucci

# Build settings
markdown: kramdown
