# Site settings
title: "Davide Reppucci | Technical project manager, team leader"
email: "davide.reppucci@gmail.com"
description: "Davide Reppucci has 10 years of experience in digital projects and can easily handle a project combining business, design and technical requirements in a high-quality final solution."
keywords: "web project management, team management, delivery management, development, techical project manager, team leader, front-end, seo, social media marketing"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dreppucci.github.io" # the base hostname & protocol for your site
twitter_username: "davidereppucci"
github_username:  "dreppucci"
permalink: pretty
collections:
  works:
    output: true
    permalink: /works/:path/


# Build settings
markdown: "kramdown"
exclude: ['Gemfile']
include: ['.htaccess']
gems: [jekyll-sitemap, jekyll-assets]
sass:
  style: compressed
assets:
  compress:
    css: true
    js: true
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all